import { PubSub } from 'graphql-subscriptions';

export const pubsub = new PubSub();

export const TOPICS = {
  MESSAGE_ADDED: 'MESSAGE_ADDED',
  TYPING_STATUS: 'TYPING_STATUS',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  FRIEND_REQUEST_RECEIVED: 'FRIEND_REQUEST_RECEIVED',
  FRIEND_REQUEST_RESPONDED: 'FRIEND_REQUEST_RESPONDED',
  POST_UPDATED: 'POST_UPDATED',
  POST_INTERACTION: 'POST_INTERACTION'
} as const;

